services:
  mysql:
    image: "mysql:5.7"
    environment:
      #MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      #MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "votacao"
      MYSQL_USER: "local_user"
      MYSQL_PASSWORD: "local_password"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
  mailpit:
    image: "axllent/mailpit:v1.21"
    ports:
      - "8025:8025"
      - "1025:1025"
